### ISSUE TITLE
Using webworkers  and wasm apprach generates browser out of memory on large files

### ISSUE THREAD

**Issue by Medo-85** [IFCjs/web-ifc-three#93] opened 2022-03-25 12:50 UTC
If I use the webworkers with wasm approach with large files like above 200mb the browser display this page
![image](https://user-images.githubusercontent.com/80624459/160123219-d7ed5475-c4d3-4788-950f-988a0e44bd62.png)
Also if I don't use the webworkers it works fine

**Comment by agviegas** [comment] 2022-03-29 09:15
Hi! Unfortunately, webworkers make it necessary to serialize data, and that has a limitation. 

We are putting toguether a workflow for bigger files that involve exporting the models to GLTF+JSON. That solves all performance issues for all use cases (models load aprox 10 times faster) and make the whole thing much more scalable. All the tools will work with this workflow as well. I'm putting toguether a tutorial to show how this works, hopefully it will useful for this use case 🙂 

I'm closing this because we can't solve the serialization limit, but stay tuned to our publications / discord for this tutorial.

**Closed by agviegas** 2022-03-29 09:15 UTC

**Comment by MattiasOlssonNikDev** [comment] 2022-03-29 09:34
Hi thanks for you answer! I am having a similar problem with an app to validate properties, calling ifcManager.getAllItemsOfType then looping and calling getItemProperties, getPropertySets, getMaterialsProperties and getTypeProperties and then validating the properties.

I'm trying to run my own webworkers and than partition what elements the workers are to process. But the memory runs out when all the workers try to serialize the data file. But I was wondering if there is a way to do this with text data only? Sense I'm not using the 3d renderer so I don't need the GLTF that is going to be in your new workflow but I still need to process big files. Or maybe there is a better way to loop over all data in a file that I'm not aware of?

**Comment by agviegas** [comment] 2022-03-29 10:08
The problem is that given that IFC is a text file and due to the current implementation, all properties+geometry must be loaded in memory to read them. This is not very scalable. 

So these days we have put toguether an exporter that converts an IFC into an array of glTF files (geometry) + a JSON (properties). This way, geometry loading gets exponentially faster, users can only load the geometry they want and properties can be used to populate a database, which is a much more efficient system to retrieve data. The downside of this approach is that you need a backend (or file system in case you are using electron) to store this data. But IMO it's a small price to pay to reduce memory usage by half and increase loading speed by 10. 😄 I started making the tutorial for that today. We know that a lot of people want to build scalable BIM platforms, and we will definitely cover it!

**Comment by Medo-85** [comment] 2022-04-13 19:40
> Hi! Unfortunately, webworkers make it necessary to serialize data, and that has a limitation.
> 
> We are putting toguether a workflow for bigger files that involve exporting the models to GLTF+JSON. That solves all performance issues for all use cases (models load aprox 10 times faster) and make the whole thing much more scalable. All the tools will work with this workflow as well. I'm putting toguether a tutorial to show how this works, hopefully it will useful for this use case 🙂
> 
> I'm closing this because we can't solve the serialization limit, but stay tuned to our publications / discord for this tutorial.

Hi @agviegas thanks for clarification, may you please describe the the workflow of GLTF+JSON like in steps so I may figure it out until the tutorial comes out.

**Comment by agviegas** [comment] 2022-04-17 19:32
Sure, you can find the [export example](https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-viewer/gltf-export) and the [import example](https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-viewer/gltf-import) in the hello-world repository. They are also published on github pages, so you can take a look at the [live examples](https://ifcjs.github.io/hello-world/examples/web-ifc-viewer/gltf-import/) (just change the URL by the github pages URL).
